title: Eduardo Maia
email: eduvimaia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Codebeers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://emaiax.me" # the base hostname & protocol for your site
twitter_username: emaiax
github_username:  emaiax

timezone: "America/Sao_Paulo"

permalink: none
markdown: kramdown
highlighter: pygments

gems:
  - jemoji
